on:
  workflow_run:
    workflows: ["brew test-bot"]
    types:
      - "completed"
    branches-ignore: main
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: pr-pull